about/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.about.mainpage,name='about'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.blog.mainpage, name='blog'),
	path('post/<int:bn>',views.blog.blogpost, name='blogpost'),
	path('create',views.blog.create, name='create')
	]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<int:qid>',views.contact.us,name='contact'),
	path('enterprise',views.contact.enterprise,name='contactEnterprise'),
	path('rush',views.contact.rush,name='contactRush')
]

schedule/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('schedule/<int:qid>/<int:year>/<int:month>/<int:day>/<str:start>/<str:end>',views.scheduler.confirm,name='schedule'),
	path('checkout/<int:qid>/<int:year>/<int:month>/<int:day>/<str:start>/<str:end>',views.checkout.payment,name='checkout'),
	path('checkout/create-payment-intent',views.checkout.createpayment, name='create-payment-intent'),
	path('checkout/payment-complete',views.checkout.paymentcomplete, name='payment-complete'),
	path('cancel/<int:uid>/<int:year>/<int:month>/<int:day>/<str:start>',views.scheduler.cancel,name='cancel'),
	path('forward/<int:qid>/<int:year>/<int:month>/<int:day>/<str:start>',views.scheduler.forward,name='forward'),
]

about/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
#from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class post(models.Model):
	bn = models.AutoField(primary_key=True)
	statuses = ((1,'Published'),(0,'Hidden'))
	
	title = models.CharField(max_length=255)
	status = models.IntegerField(choices=statuses)
	author = models.IntegerField()
	name = models.CharField(max_length=255)
	body = RichTextUploadingField(blank=True,null=True)
	post_date = models.DateField(auto_now_add=True)
	
	class Meta:
		ordering = ['-post_date']

class comment(models.Model):
	statuses = ((1,'Published'),(0,'Hidden'))
	bcn = models.AutoField(primary_key=True)
	bn = models.IntegerField()
	status = models.IntegerField(choices=statuses)
	author = models.IntegerField()
	name = models.CharField(max_length=255)
	body = RichTextField(blank=True,null=True)
	post_date = models.DateField(auto_now_add=True)
	
	class Meta:
		ordering = ['-post_date']
	

contact/models.py
from django.db import models

# Create your models here.
class contacts(models.Model):
	name = models.CharField(max_length=255,blank=False)
	email = models.CharField(max_length=255,blank=False)
	directed = models.IntegerField(default=0,blank=True)
	comment = models.TextField()
	contactEmail = models.IntegerField(default=0)

schedule/models.py
from django.db import models

# Create your models here.
class forwards(models.Model):
	qn = models.IntegerField()
	year = models.IntegerField()
	month = models.IntegerField()
	date = models.IntegerField()
	start = models.CharField(max_length=12)
	name = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	sent = models.IntegerField(default=0)
	url = models.CharField(max_length = 255)

solutions/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class qinfo(models.Model):
	prefixes = (('Mr.','Mr.'),('Mrs.','Mrs.'),('Ms.','Ms.'),('Dr.','Dr.'),)
	suffixes = (('PhD','PhD'),('M.D.','M.D.'),)
	categories = (('medicine','Medicine'),)
	actives = ((1,'Yes'),(0,'No'),)
	competency = ((1,'Yes'),(0,'No'))
	
	#qn = models.AutoField(primary_key=True)
	#user = models.OneToOneField(User, on_delete=models.CASCADE) #DONT TURN THIS ON IT WILL BREAK THE MODEL
	qn = models.IntegerField(primary_key=True)
	active = models.IntegerField(choices=actives,default=1)
	prefix = models.CharField(max_length=255,choices=prefixes,blank=True)
	first = models.CharField(max_length=255)
	last = models.CharField(max_length=255)
	suffix = models.CharField(max_length=255,choices=suffixes,blank=True)
	category = models.CharField(max_length=255,choices=categories)
	servicelinedev = models.IntegerField(choices=competency,default=0)
	capitalplan = models.IntegerField(choices=competency,default=0)
	pysicianrecruitment = models.IntegerField(choices=competency,default=0)
	processimprove = models.IntegerField(choices=competency,default=0)
	productivity = models.IntegerField(choices=competency,default=0)
	operationsfinance = models.IntegerField(choices=competency,default=0)
	leadingmeetings = models.IntegerField(choices=competency,default=0)
	dataanalysis = models.IntegerField(choices=competency,default=0)
	teamcourses = models.IntegerField(choices=competency,default=0)
	personalleadership = models.IntegerField(choices=competency,default=0)
	personalitytypes = models.IntegerField(choices=competency,default=0)
	tempassignments = models.IntegerField(choices=competency,default=0)
	special1 = models.CharField(max_length=255,blank=False)
	special2 = models.CharField(max_length=255,blank=False)
	special3 = models.CharField(max_length=255,blank=False)
	special4 = models.CharField(max_length=255,blank=False)
	special5 = models.CharField(max_length=255,blank=False)
	description = models.CharField(max_length=255,blank=False)
	bio = models.TextField()
	linkedin = models.CharField(max_length=255,null=True,blank=True)
	yearexp = models.IntegerField(blank=False)
	email = models.CharField(max_length=255,blank=False,default='example@gmail.com')
	cost = models.IntegerField(default=100)
	
	#def __str__(self):
	#	return str(self.qn)
	
	def get_absolute_url(self):
		return reverse('q',args=[str(self.qn)])
		
	def __str__(self):
		#fullnamestr = self.prefix + '' + self.first + '' + self.last + '' + self.suffix
		return f'{self.prefix} {self.first} {self.last} {self.suffix}'

blog/forms.py
from django import forms
from .models import post, comment

class blogposts(forms.ModelForm):
	class Meta:
		model = post
		fields = ['title','body']

class commentposts(forms.ModelForm):
	class Meta:
		model = comment
		fields = ['body']

contact/forms.py
from django import forms
from .models import contacts

class contactUs(forms.ModelForm):
	class Meta:
		model = contacts
		fields = ['name','email','comment']

profiles/forms.py
from django import forms

class recuravail(forms.Form):
	day = forms.ChoiceField(choices=[('monday','Monday'),('tuesday','Tuesday'),('wednesday','Wednesday'),('thursday','Thursday'),('friday','Friday'),('saturday','Saturday'),('sunday','Sunday')])
	hour = forms.ChoiceField(choices=[(x, x) for x in range(1, 13)])
	minute = forms.ChoiceField(choices=[('00','00'),('15','15'),('30','30'),('45','45')])
	half = forms.ChoiceField(choices=[('AM','AM'),('PM','PM')])
	
	
class individualavail(forms.Form):
	month = forms.ChoiceField(choices=[(1,'January'),(2,'February'),(3,'March'),(4,'April'),(5,'May'),(6,'June'),(7,'July'),(8,'August'),(9,'September'),(10,'October'),(11,'November'),(12,'December')])
	date = forms.ChoiceField(choices=[(x, x) for x in range(1, 32)])
	hour = forms.ChoiceField(choices=[(x, x) for x in range(1, 13)])
	minute = forms.ChoiceField(choices=[('00','00'),('15','15'),('30','30'),('45','45')])
	half = forms.ChoiceField(choices=[('AM','AM'),('PM','PM')])

schedule/forms.py
from django import forms
from .models import forwards

class forwardQA(forms.ModelForm):
	class Meta:
		model = forwards
		fields = ['name','email']

about/views.py
from django.shortcuts import render

# Create your views here.
class about():
	def mainpage(request):
		context = {}
		return render(request,'about.html',context=context)

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import post, comment
import datetime as dt
from .forms import blogposts, commentposts
from solutions.models import qinfo
import datetime as dt
# Create your views here.
class blog():
	def mainpage(request):
		filter_kwargs = {
		'status__exact': 1
		}
		posts = post.objects.filter(**filter_kwargs)
		context = {'blogposts': posts}
		return render(request,'blog.html',context=context)
	
	@login_required
	def blogpost(request,bn):
		filter_kwargs = {
		'bn__exact': bn,
		'status__exact': 1
		}
		posts = post.objects.filter(**filter_kwargs)
		comments = comment.objects.filter(**filter_kwargs)
		
		form = commentposts
		if request.method=='POST':
			form = commentposts(data=request.POST)
			if form.is_valid():
				commentpost = form.save(commit=False)
				commentpost.author = request.user.id
				commentpost.status = 1
				commentpost.bn = bn
				try:
					q = qinfo.objects.get(qn=int(request.user.id))
					commentpost.name = q.__str__()
				except Exception:
					c = User.objects.get(id=int(request.user.id))
					commentpost.name = c.first_name + ' ' + c.last_name
				commentpost.save()
				return redirect('blogpost', bn=bn)
		
		now = dt.datetime.now()
		now = now.strftime('%Y-%m-%d')
		context = {
			'blogpost': posts[0],
			'now': now,
			'comments': comments,
			'form': form,
			}
		return render(request,'blogpost.html',context=context)
	
	@login_required
	def create(request):
		form = blogposts
		if request.method=='POST':
			form = blogposts(data=request.POST)
			if form.is_valid():
				blogpost = form.save(commit=False)
				blogpost.author = request.user.id
				blogpost.status = 1
				try:
					q = qinfo.objects.get(qn=request.user.id)
					blogpost.name = q.__str__()
				except Exception:
					c = User.objects.get(id=request.user.id)
					blogpost.name = c.first_name + ' ' + c.last_name
				blogpost.save()
				
				now = dt.datetime.now()
				now = now.strftime('%Y-%m-%d')
				return redirect('account', getq=request.user.id) 
		context = {
			'form': form
			}
		return render(request, 'blogcreate.html', context=context)
	

contact/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import contactUs
from django.core import mail
from solutions.models import qinfo

# Create your views here.
class contact():
    def us(request,qid):
        form = contactUs
        if request.method=='POST':
            form = contactUs(data=request.POST)
            if form.is_valid():             
                contact = form.save(commit=False)
                name = form.cleaned_data.get('name')
                email = form.cleaned_data.get('email')
                comment =  form.cleaned_data.get('comment')
                
                contact.directed = qid
                contact.contactEmail = 1
                contact.save()
                """
                subject = 'Contact Request from ' + name
                plain_message = 'Sent on behalf of ' + email + '\n' + comment
                
                if qid==0:
                    to_email = ('coltonjameshail@gmail.com',)
                else:
                    filter_kwargs = {
                    'qn__exact': qid,
                    }
                    q = qinfo.objects.filter(**filter_kwargs)
                    to_email = (q[0].email,)
                mail.send_mail(subject,plain_message,'',to_email,html_message=None)
                """
                
                messages.success(request, "Thank you for your message! We will get back to you shortly.")
                
            else:
                messages.error(request, "Please fill out all forms.")
                
        else:
            if qid!=0:
                messages.info(request, 'Please fill out the form below. ' + qinfo.objects.get(qn=qid).__str__() + ' will respond shortly')
        context = {
            'form': form,
            'qid': qid
            }
        return render(request, 'contact.html', context)
    
    def enterprise(request):
        messages.info(request,'Let us know how we can help your organization and our enterprise team will reach out shortly.')
        return redirect('contact', qid=0)
        
    def rush(request):
        messages.info(request,'RUSH REQUEST: please provide a description of how we can help you and our action team will contact you within a few hours.')
        return redirect('contact', qid=0)

solutions/views.py
from django.shortcuts import render
from solutions.models import qinfo
import datetime as dt
#import requests
# Create your views here

def solutions(request):
	context = {
		'servicelinedev': 'servicelinedev',
		'capitalplan': 'capitalplan',
		'pysicianrecruitment': 'pysicianrecruitment',
		'processimprove': 'processimprove',
		'productivity': 'productivity',
		'operationsfinance': 'operationsfinance',
		'leadingmeetings': 'leadingmeetings',
		'dataanalysis': 'dataanalysis',
		'teamcourses': 'teamcourses',
		'personalleadership': 'personalleadership',
		'personalitytypes': 'personalitytypes',
		'tempassignments': 'tempassignments',
		}
	return render(request, 'solutions.html', context=context)

class qsearch():
	model = qinfo
	template_name = 'qlist.html'
	#FUTURE paginiate_by = 20
	queryset = qinfo.objects.filter()
	
	def get_search(request, subcat):
		filter_kwargs = {
			subcat + '__contains': 1,
			'active__exact': 1
			}
		qs = qinfo.objects.filter(**filter_kwargs)
		now = dt.datetime.now()
		now = now.strftime('%Y-%m-%d')
		context = {
			'qs': qs,
			'now': now
			}
		return render(request, 'qlist.html', context=context)
	
	def strsearch(request):
		queries = request.GET.get('searchfield').split()
		results = qinfo.objects.none()
		for query in queries:
			filter_kwargs = {
				'special1__icontains': query,
				'active__exact': 1
				}
			result1 = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'special2__icontains': query,
				'active__exact': 1
				}
			result2 = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'special3__icontains': query,
				'active__exact': 1
				}
			result3 = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'special4__icontains': query,
				'active__exact': 1
				}
			result4 = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'special5__icontains': query,
				'active__exact': 1
				}
			result5 = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'description__icontains': query,
				'active__exact': 1
				}
			resultD = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'bio__icontains': query,
				'active__exact': 1
				}
			resultB = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'first__icontains': query,
				'active__exact': 1
				}
			resultF = qinfo.objects.filter(**filter_kwargs)
			
			filter_kwargs = {
				'last__icontains': query,
				'active__exact': 1
				}
			resultL = qinfo.objects.filter(**filter_kwargs)
		
			result = result1 | result2 | result3 | result4 | result5 | resultD | resultB | resultF | resultL
			results = results | result
		
		now = dt.datetime.now()
		now = now.strftime('%Y-%m-%d')
		context = {
			'qs': results,
			'now': now
			}
		return render(request, 'qlist.html', context=context)

	def allqs():
		queryset = qinfo.objects.filter(active=1)
		return queryset

	def qlist(request):
		qs = qsearch.allqs()
		now = dt.datetime.now()
		now = now.strftime('%Y-%m-%d')
		context = {
			'qs': qs,
			'now': now
			}
		return render(request, 'qlist.html', context=context)
	

		

templates/setavail.html
{% extends "base_generic.html" %}

{% block content %}
  {% load static %}
  
    <div class="section cc-home-wrap">
    <div class="div-block-8">
      <div class="columns-3 w-row">
        <div class="column-4 w-col w-col-6">
          <div>
            <div class="w-form">
              <form action="{% url 'availability' getq=qn availstart=now %}" method="post" id="wf-form-recuravail" name="wf-form-recuravail" data-name="recuravail" class="form-4">
			    {% csrf_token %}
                <div class="text-block-49">Recurring Availability</div>
                <div class="div-block-49">
                  <div class="text-block-54">Day</div>
                  <div class="div-block-70">{{ recurform.day }}</div>
                  <div class="text-block-54">Start Time</div>
                  <div class="div-block-71">{{ recurform.hour }}</div>
                  <div class="text-block-48"> : </div>
                  <div class="div-block-72">{{ recurform.minute }}</div>
                  <div class="div-block-73">{{ recurform.half }}</div>
                </div><input name="recuravail" type="submit" value="Submit" data-wait="Please wait..." class="submit-button-10 w-button">
              </form>
            </div>
          </div>
        </div>
		  <style>
			#id_day {
				display: inline-block;
				width: 100%;
				border: 1px solid #e4e4e4;
				border-radius: 0px;
				-webkit-transition: border-color 400ms ease;
				transition: border-color 400ms ease;
			}

			#id_hour {
				display: inline-block;
				width: 100%;
				border: 1px solid #e4e4e4;
				border-radius: 0px;
				-webkit-transition: border-color 400ms ease;
				transition: border-color 400ms ease;
			}
			
			#id_minute {
				display: inline-block;
				width: 100%;
				border: 1px solid #e4e4e4;
				border-radius: 0px;
				-webkit-transition: border-color 400ms ease;
				transition: border-color 400ms ease;
			}
			
			#id_half {
				display: inline-block;
				width: 100%;
				border: 1px solid #e4e4e4;
				border-radius: 0px;
				-webkit-transition: border-color 400ms ease;
				transition: border-color 400ms ease;
			}
		  </style>
        <div class="column w-col w-col-6">
          <div class="form-block-5 w-form">
            <form action="{% url 'availability' getq=qn availstart=now %}" method="post" id="wf-form-individualavail" name="wf-form-individualavail" data-name="individualavail" class="form-5">
			  {% csrf_token %}
              <div class="text-block-50">Individual Availability</div>
              <div class="text-block-56">Month</div>
              <div class="text-block-52">Date</div>
              <div class="div-block-66">
                <div class="div-block-74">{{ indyform.month }}</div>
                <div class="text-block-51">/</div>
                <div class="div-block-75">{{ indyform.date }}</div>
                <div class="text-block-59">Start Time</div>
                <div class="div-block-76">{{ indyform.hour }}</div>
                <div class="text-block-53">:</div>
                <div class="div-block-77">{{ indyform.minute }}</div>
                <div class="div-block-78">{{ indyform.half }}</div>
              </div><input name="indyavail" type="submit" value="Submit" data-wait="Please wait..." class="submit-button-11 w-button">
            </form>
          </div>
        </div>
      </div>
      <div class="div-block-50"></div>
    </div>
  </div>
  
    <style>
	#id_date {
	    display: inline-block;
		width: 100%;
		border: 1px solid #e4e4e4;
		border-radius: 0px;
		-webkit-transition: border-color 400ms ease;
		transition: border-color 400ms ease;
	}
	
	#id_month {
	    display: inline-block;
		width: 100%;
		border: 1px solid #e4e4e4;
		border-radius: 0px;
		-webkit-transition: border-color 400ms ease;
		transition: border-color 400ms ease;
	}
	
	#id_hour {
	    display: inline-block;
		width: 100%;
		border: 1px solid #e4e4e4;
		border-radius: 0px;
		-webkit-transition: border-color 400ms ease;
		transition: border-color 400ms ease;
	}
	
	#id_minute {
	    display: inline-block;
		width: 100%;
		border: 1px solid #e4e4e4;
		border-radius: 0px;
		-webkit-transition: border-color 400ms ease;
		transition: border-color 400ms ease;
	}
	
	#id_half {
	    display: inline-block;
		width: 100%;
		border: 1px solid #e4e4e4;
		border-radius: 0px;
		-webkit-transition: border-color 400ms ease;
		transition: border-color 400ms ease;
	}
  </style>
  
  <div id="qa" class="section-2">
    <div class="div-block-17">
      <div class="text-block-17">Recurring Times</div>
    </div>
    <div class="div-block-18">
      <div class="w-layout-grid grid-3">
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Monday</div>
          </div>
          <div>
		    {% for start in recurs.monday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Tuesday</div>
          </div>
          <div>
		    {% for start in recurs.tuesday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Wednesday</div>
          </div>
          <div>
		    {% for start in recurs.wednesday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Thursday</div>
          </div>
          <div>
		    {% for start in recurs.thursday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Friday</div>
          </div>
          <div>
		    {% for start in recurs.friday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Saturday</div>
          </div>
          <div>
		    {% for start in recurs.saturday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">Sunday</div>
          </div>
          <div>
		    {% for start in recurs.sunday %}
              <a href="#" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a>
			{% endfor %}
          </div>
        </div>
      </div>
    </div>
	<div class="text-block-65">Click on a recurring time to delete it - note it will not cancel any already scheduled times.</div>
  </div>
  <div id="qa" class="section-2">
    <div class="div-block-17">
      <div class="w-row">
        <div class="w-col w-col-4">
          <a href="{% url 'availability' getq=qn availstart=prevweek %}" class="button-5 w-button">Previous Week</a>
        </div>
        <div class="w-col w-col-4">
          <div class="text-block-17">Full Schedule</div>
        </div>
        <div class="w-col w-col-4">
          <a href="{% url 'availability' getq=qn availstart=nextweek %}" class="button-6 w-button">Next Week</a>
        </div>
      </div>
    </div>
    <div class="div-block-18">
      <div class="w-layout-grid grid-3">
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.first.month }}/{{ avails.first.day }}</div>
          </div>
		  {% for start in avails.firststarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.second.month }}/{{ avails.second.day }}</div>
          </div>
  		  {% for start in avails.secondstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.third.month }}/{{ avails.third.day }}</div>
          </div>
		  {% for start in avails.thirdstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.fourth.month }}/{{ avails.fourth.day }}</div>
          </div>
		  {% for start in avails.fourthstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.fifth.month }}/{{ avails.fifth.day }}</div>
          </div>
		  {% for start in avails.fifthstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.sixth.month }}/{{ avails.sixth.day }}</div>
          </div>
		  {% for start in avails.sixthstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
        <div class="div-block-15">
          <div>
            <div class="text-block-18">{{ avails.seventh.month }}/{{ avails.seventh.day }}</div>
          </div>
		  {% for start in avails.seventhstarts %}
			{% if start.status == 0 %}
			  <a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-24">{{ start.starttime }} - {{ start.endtime }}</a>
			{% else %}
			  <div><a href="{% url 'unset' getq=qn availstart=now year=start.year month=start.month date=start.date starttime=start.starttime %}" class="link-8">{{ start.starttime }} - {{ start.endtime }}</a></div>
			{% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
	<div class="text-block-65">Click on a scheduled time to cancel it (the time will show with a strikethrough) - click again to reactivate.</div>
  </div>
  
{% endblock %}